use crate::field::Field;

///
/// Field such that every finite degree extension field is separable.
/// 
/// This is equivalent to the following:
///  - Every irreducible polynomial is square-free (over the algebraic closure)
///  - Every finite-degree field extension is simple, i.e. generated by a single element
/// 
pub trait PerfectField: Field {}
